### ISSUE TITLE
Minor comments

### ISSUE THREAD

**Issue by marmarek** [niccokunzmann/qvm-expose-port#1]
https://github.com/niccokunzmann/qvm-expose-port/blob/4aff1cb5f335411c75ca87a4eb82c20f74b526f5/qvm-expose-port#L97

Better use `-u root` option instead of sudo.

https://github.com/niccokunzmann/qvm-expose-port/blob/4aff1cb5f335411c75ca87a4eb82c20f74b526f5/qvm-expose-port#L84

There is `qvm-check` tool specifically for this purpose.

**Comment by niccokunzmann** [comment]
Thanks @marmarek I included them!
